### ISSUE TITLE
/msg and /r not work

### ISSUE THREAD

**Issue by mat41997** [AuraDevelopmentTeam/BungeeChat2#24]
timings
https://timings.aikar.co/?id=a3c6f4f1145f4597b511ba136d88ed7b

plugin version
```
BungeeChat-2.1.6.855
```

permission player haven
```
bungeechat.command.msg
```

config
```
    Messenger:
      enabled: true
      filterMessages: false
      aliases:
        message:
          - msg
          - tell
          - m
          - w
          - whisper
        reply:
          - r
        msgtoggle:
          - mtoggle
```

player not have permission to use that command
you can fix this?
