### ISSUE TITLE
[Idea]: clickable messages

### ISSUE THREAD

**Issue by RedstoneFuture** [AuraDevelopmentTeam/BungeeChat2#44]
#### Issue Description:

clickable messages: e.g.

```
  placeholder1: #clickable player-name
    text: '%sender_name%'
    click-event:
      action: 'run_command'
      value: '/playerinfo %sender_name%'
    hover-event:
      action: 'show_text'
      value: '&8/playerinfo %sender_name%'
```

`  globalChat: "&7[&fGlobal&7] %sender_prefix% %placeholder1%&f: %message%"`

____
#### Affected Versions:

- Minecraft: 1.12.2
- BungeeChat:  2.1.6.855
