### ISSUE TITLE
Filter commands in logging isn't working

### ISSUE THREAD

**Issue by DmitryRendov** [AuraDevelopmentTeam/BungeeChat2#76]
#### Issue Description: 
I have these entries as in the bungee console so in log file
```
11:28:47 [INFO] [BungeeChat] COMMAND > lobby > WDemon: /l 111222
11:28:51 [INFO] [BungeeChat] COMMAND > lobby > WDemon: /login
11:28:55 [INFO] [BungeeChat] COMMAND > lobby > WDemon: /login 111222
11:29:02 [INFO] [BungeeChat] COMMAND > lobby > WDemon: /l 2222333
```

even with this config part on my bungee:
```
    ChatLogging:
      enabled: true
      privateMessages: true
      console: true
      file: true
      logFile: "logs/%year%-%month%-%day%-chat.log"
      filteredCommands:
        - login
        - l
        - changepass
        - changepassword
        - help
```

#### What happens:
Security issue

#### What you expected to happen:
Filter should work

____
#### Affected Versions: 

- Minecraft: git-Spigot-2b0e71c-4a24108 (MC: 1.13)
- BungeeChat:  2.1.6.855
- Other related plugins: git:BungeeCord-Bootstrap:1.13-SNAPSHOT:9ea82e9:1351

#### Your most recent log or stack trace file where the issue was present: 

```
<!-- Or stack trace here (Remove this if you don't put anything here!) -->
```
